var imgArr = ['images/cover.png', 'images/cover_3.png', 'images/cover_2.png', 'images/cover_1.png',
	'images/cover_4.png', 'images/content.png', 'images/cover_arrow.png', 'images/cover_arrow_right.png',
	'images/title_1.png', 'images/cover_font_1.png', 'images/cover_font_2.png', 'images/cover_font_3.png',
	'images/cover_font_4.png', 'images/cover_font_5.png', 'images/footerCopyRight.png',
	'images/footerLink.png', 'images/website.png', 'images/page_1_1.png', 'images/page_1_2.png',
	'images/page_1_3.png', 'images/page_1_4.png', 'images/page_1_5.png', 'images/page_1_6.png',
	'images/page_1_7.png', 'images/page_1_8.png', 'images/page_1_9.png', 'images/page_1_10.png',
	'images/page_1_11.png', 'images/page_1_12.png', 'images/page_1_13.png', 'images/page_1_14.png',
	'images/page_1_15.png', 'images/page_1_16.png', 'images/page_1_17.png', 'images/page_1_18.png',
	'images/page_1_19.png', 'images/page_1_20.png', 'images/page_1_21.png', 'images/page_1_22.png',
	'images/page_1_23.png', 'images/page_1_24.png', 'images/page_1_25.png', 'images/page_1_26.png',
	'images/page_1_27.png', 'images/page_1_28.png', 'images/page_1_29.png', 'images/page_1_30.png',
	'images/page_1_31.png', 'images/page_1_32.png', 'images/page_1_33.png', 'images/page_1_34.png',
	'images/page_1_35.png', 'images/page_1_36.png', 'images/page_2_0.png', 'images/page_2_1.png',
	'images/page_2_2.png', 'images/page_2_3.png', 'images/page_2_4.png', 'images/page_2_5.png',
	'images/page_2_6.png', 'images/page_2_7.png', 'images/page_2_8.png', 'images/page_2_9.png',
	'images/page_2_10.png', 'images/page_2_11.png', 'images/page_2_12.png', 'images/page_2_13.png',
	'images/page_2_14.png', 'images/page_3_1.png', 'images/page_3_1.png', 'images/page_3_2.png',
	'images/page_3_3.png', 'images/page_3_4.png', 'images/page_3_5.png', 'images/page_3_6.png',
	'images/page_3_7.png', 'images/page_3_8.png', 'images/page_3_9.png', 'images/page_3_10.png',
	'images/page_3_11.png', 'images/page_3_12.png', 'images/page_3_13.png', 'images/page_3_14.png',
	'images/page_3_15.png', 'images/page_3_16.png', 'images/page_3_17.png', 'images/page_3_18.png',
	'images/page_3_19.png', 'images/page_3_20.png', 'images/page_3_21.png', 'images/page_4_1.png',
	'images/page_4_2.png', 'images/page_4_3.png', 'images/page_4_4.png', 'images/page_4_5.png',
	'images/page_4_6.png', 'images/page_4_7.png', 'images/page_4_8.png', 'images/page_4_9.png',
	'images/page_4_10.png', 'images/page_4_11.png', 'images/page_4_12.png', 'images/page_5_1.png',
	'images/page_5_2.png', 'images/page_5_3.png', 'images/page_5_4.png', 'images/page_5_5.png',
	'images/page_5_6.png', 'images/page_5_7.png', 'images/page_5_8.png', 'images/page_5_9.png',
	'images/page_5_10.png', 'images/page_5_11.png', 'images/page_5_12.png'

];